
target_name ?= zcash

include ../Makefile.build

ZCASH_VERSION=v1.0.14

zcash_clone:

zcash_config:

zcash_build:
	( cd zencash; \
		LIBTOOLIZE=glibtoolize ./zcutil/build-mac-clang.sh --disable-libs; \
	)

zcash_install:

zcash_uninstall:

zcash_clean:

zcash_distclean:
